export const CATEGORY_OPTIONS = [
  "Smartphone",
  "Tablet",
  "Notebook",
  "Computador",
  "Monitor",
  "Impressora",
  "Console",
  "Controle / Joystick",
  "TV",
  "Câmera",
  "Fone / Headset",
  "Caixa de Som",
  "Smartwatch",
  "Roteador / Modem",
  "Outros",
];

export const DEFECTS_BY_CATEGORY: Record<string, string[]> = {
  Smartphone: [
    "Tela trincada",
    "Tela com manchas / pixels mortos",
    "Touch não responde",
    "Bateria viciada / descarrega rápido",
    "Não carrega",
    "Conector de carga danificado",
    "Alto-falante com defeito",
    "Microfone não funciona",
    "Câmera traseira com defeito",
    "Câmera frontal com defeito",
    "Botões físicos travando",
    "Face ID / biometria não funciona",
    "Sinal de rede fraco",
    "Wi-Fi / Bluetooth instável",
    "Travamentos / reinício",
    "Conta iCloud / Google bloqueada",
    "Carcaça amassada / arranhada",
    "Molhado / oxidado",
  ],
  Tablet: [
    "Tela trincada",
    "Tela com manchas / pixels mortos",
    "Touch não responde",
    "Bateria viciada",
    "Não carrega",
    "Conector de carga danificado",
    "Alto-falante com defeito",
    "Câmera com defeito",
    "Botões físicos travando",
    "Wi-Fi / Bluetooth instável",
    "Travamentos / reinício",
    "Conta bloqueada",
    "Carcaça amassada",
    "Molhado / oxidado",
  ],
  Notebook: [
    "Não liga",
    "Liga e desliga sozinho",
    "Tela trincada",
    "Tela com manchas / faixas",
    "Bateria viciada / não segura carga",
    "Carregador / fonte com defeito",
    "Conector de carga frouxo",
    "Teclado com teclas falhando",
    "Touchpad não responde",
    "Áudio sem som",
    "Webcam não funciona",
    "Portas USB com defeito",
    "HDMI / vídeo externo sem sinal",
    "Superaquecimento",
    "Cooler com barulho",
    "Travamentos / lentidão",
    "HD / SSD com defeito",
    "Dobradiça quebrada",
    "Carcaça quebrada",
    "Molhado / oxidado",
  ],
  Computador: [
    "Não liga",
    "Liga mas não dá vídeo",
    "Reinicia sozinho",
    "Travamentos",
    "Superaquecimento",
    "Coolers / ventoinhas com barulho",
    "Fonte com defeito",
    "HD / SSD com defeito",
    "Memória RAM com defeito",
    "Placa-mãe com defeito",
    "Placa de vídeo com defeito",
    "Portas USB com defeito",
    "Áudio sem som",
    "Gabinete danificado",
  ],
  Console: [
    "Não liga",
    "Liga e desliga sozinho",
    "Superaquecimento",
    "Leitor de disco não funciona",
    "Não lê jogos",
    "Não dá vídeo / HDMI sem sinal",
    "Áudio com defeito",
    "Travamentos",
    "Cooler / ventoinha com barulho",
    "Porta de controle com defeito",
    "Wi-Fi / rede com defeito",
    "Fonte com defeito",
    "Carcaça danificada",
    "Conta bloqueada",
  ],
  "Controle / Joystick": [
    "Analógico com drift",
    "Analógico travando",
    "Botões não respondem",
    "Gatilhos (L2/R2) com defeito",
    "Não conecta via Bluetooth",
    "Não conecta via cabo",
    "Bateria viciada",
    "Não carrega",
    "Vibração não funciona",
    "Carcaça quebrada",
  ],
  TV: [
    "Não liga",
    "Tela trincada",
    "Tela com manchas / faixas",
    "Sem imagem",
    "Sem áudio",
    "Portas HDMI com defeito",
    "Portas USB com defeito",
    "Wi-Fi / Smart TV não conecta",
    "Controle remoto não funciona",
    "Travamentos",
    "Carcaça danificada",
  ],
  Outros: [
    "Não liga",
    "Não carrega",
    "Bateria viciada",
    "Áudio com defeito",
    "Tela com defeito",
    "Botões com defeito",
    "Carcaça danificada",
    "Molhado / oxidado",
    "Travamentos",
  ],
};

DEFECTS_BY_CATEGORY["Monitor"] = [
  "Não liga",
  "Tela trincada",
  "Tela com manchas / faixas",
  "Pixels mortos",
  "Sem imagem",
  "Portas HDMI / VGA / DP com defeito",
  "Botões físicos travando",
  "Carcaça danificada",
];

DEFECTS_BY_CATEGORY["Impressora"] = [
  "Não liga",
  "Não imprime",
  "Atola papel",
  "Cabeçote entupido",
  "Impressão com falhas / riscos",
  "Scanner com defeito",
  "Wi-Fi não conecta",
  "Erro de cartucho / toner",
  "Display com defeito",
  "Carcaça danificada",
];

DEFECTS_BY_CATEGORY["Câmera"] = [
  "Não liga",
  "Lente arranhada",
  "Foco não funciona",
  "Display com defeito",
  "Bateria viciada",
  "Não carrega",
  "Cartão não reconhecido",
  "Botões travando",
  "Carcaça danificada",
];

DEFECTS_BY_CATEGORY["Fone / Headset"] = [
  "Sem áudio em um lado",
  "Áudio com chiado",
  "Microfone não funciona",
  "Não conecta via Bluetooth",
  "Bateria viciada",
  "Não carrega",
  "Botões com defeito",
  "Cabo / conector danificado",
  "Carcaça quebrada",
];

DEFECTS_BY_CATEGORY["Caixa de Som"] = [
  "Não liga",
  "Sem áudio",
  "Áudio com chiado / distorção",
  "Bateria viciada",
  "Não carrega",
  "Bluetooth não conecta",
  "Entrada P2 / USB com defeito",
  "Botões com defeito",
  "Carcaça danificada",
];

DEFECTS_BY_CATEGORY["Smartwatch"] = [
  "Tela trincada",
  "Touch não responde",
  "Bateria viciada",
  "Não carrega",
  "Sensores com defeito",
  "Bluetooth não conecta",
  "Pulseira danificada",
  "Carcaça danificada",
  "Molhado / oxidado",
];

DEFECTS_BY_CATEGORY["Roteador / Modem"] = [
  "Não liga",
  "Não distribui internet",
  "Wi-Fi fraco / instável",
  "Portas LAN com defeito",
  "Fonte com defeito",
  "Travamentos / reinício",
  "Carcaça danificada",
];

export function defectsFor(category?: string | null): string[] {
  return DEFECTS_BY_CATEGORY[category || ""] || DEFECTS_BY_CATEGORY.Outros;
}